#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a qupzilla desktop='^2'
bspc rule -a Screenkey manage=off

# start apps
sxhkd &
# panel
export PATH=$PATH:~/.config/bspwm/panel/panel &
export PATH=$PATH:~/.config/bspwm/panel/panel_bar &
export PATH=$PATH:~/.config/bspwm/panel/panel_colors &
export PANEL_FIFO="/tmp/panel-fifo" &
#xterm  +sb +tb &
#xterm  +sb +tb &
xterm -fa "font_name" -fs 9  +tb &
xterm -fa "font_name" -fs 9  +tb &

#source ~/.config/bspwm/panel/bspwmrc &
export PANEL_FONT="Roboto" &

. /home/msamec/.config/bspwm/panel/clock | lemonbar -a 32 -u 2 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" -r 2 -R "$COLOR_DEFAULT_FG" &

# Photo by Moose Photos from Pexels
feh --bg-center /cygdrive/c/Users/msamec/Pictures/abstract-art-background-saturated.jpg &
